### ISSUE TITLE
couldnt think of any other way to contact you

### ISSUE THREAD

**Issue by xeome** [lombervid/dotfiles#1]
i saw in picom issues when you were showing a bug, you used cat command but its output is very different from default, how do you do that?
![image](https://user-images.githubusercontent.com/44901648/157215404-ef3e7b15-f7aa-4d1d-b1ec-f2e33adfa37b.png)

**Comment by lombervid** [comment]
Hello.

I'm really sorry for the late response. I hadn't noticed this.

That's `bat`. I just have an alias `cat='bat --paging=never'`.

https://github.com/sharkdp/bat
